version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: always
    ports:
      - "3001:3000"

  nginx-config:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/project-configs
      - /etc/nginx/conf.d:/system-nginx
      - ./.certs:/project-certs
      - /etc/nginx/certs:/system-certs
    network_mode: host
