version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: always
    expose:
      - '3001'
    ports:
      - '127.0.0.1:3001:3000'

  nginx-config:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d/craftzman.ru.conf:/etc/nginx/conf.d/craftzman.ru.conf:ro
      - ./.certs/craftzman.ru.crt:/etc/nginx/certs/craftzman.ru.crt:ro
      - ./.certs/craftzman.ru.key:/etc/nginx/certs/craftzman.ru.key:ro
    network_mode: host
